[build]
  command = "npm install && npm run build"
  publish = "out/"

[build.environment]
  NEXT_PUBLIC_AIRTABLE_API_KEY = "pat2eefeUQyk3CYjl.5518af09368c29b6c2c1ffbc7470f3de8d95f524a0e47b162075a078e58f6756"
  NEXT_PUBLIC_AIRTABLE_BASE_ID = "apptm5ErS0MOvmo7k"
  NODE_OPTIONS = "--max-old-space-size=8192"